const actionTypes = {
    START_UPDATE_USER_PROFILE : 'START_UPDATE_USER_PROFILE',
    FALIURE_USER_PROFILE : 'FALIURE_USER_PROFILE',

    START_LOGOUT_PROCESS : 'START_LOGOUT_PROCESS',
    SUCCESS_LOGOUT_PROCESS : 'SUCCESS_LOGOUT_PROCESS',
    FALIURE_LOGOUT_PROCESS : 'FALIURE_LOGOUT_PROCESS',
}

export default actionTypes