// const actionTypes = {
//     LOAD_REGISTER : 'LOAD_REGISTER',
//     LOAD_SUCCESS_REGISTER : 'LOAD_SUCCESS_REGISTER',
//     FAILURE_REGISTER : 'FAILURE_REGISTER',
//     LOAD_USERDATA : 'LOAD_USERDATA',
//     LOAD_SUCCESS_USERDATA : 'LOAD_SUCCESS_USERDATA',
//     FAILURE_USERDATA : 'FAILURE_USERDATA'
// }
// export default actionTypes
