const actionTypes = {
   
    SUCCESS_PRODUCT_DATA : 'SUCCESS_PRODUCT_DATA',
    FALIURE_PRODUCT_DATA : 'FALIURE_PRODUCT_DATA',
    LOAD_PRODUCT_DATA: 'LOAD_PRODUCT_DATA',

    SUCCESS_SELECTED_VARIANT_DATA : 'SUCCESS_SELECTED_VARIANT_DATA',

    START_ADD_TO_CART : 'START_ADD_TO_CART',
    SUCCESS_ADD_TO_CART : 'SUCCESS_ADD_TO_CART',
    FALIURE_ADD_TO_CART : 'FALIURE_ADD_TO_CART',
    EMPTY_ADD_TO_CART : 'EMPTY_ADD_TO_CART',
    
    START_ACTIVE_CART : 'START_ACTIVE_CART',
    SUCCESS_ACTIVE_CART : 'SUCCESS_ACTIVE_CART',
    FALIURE_ACTIVE_CART : 'FALIURE_ACTIVE_CART',

    START_UPDATE_CART_DATA : 'START_UPDATE_CART_DATA',
    SUCCESS_UPDATE_CART_DATA : 'SUCCESS_UPDATE_CART_DATA',
    FALIURE_UPDATE_CART_DATA : 'FALIURE_UPDATE_CART_DATA',

    DELETE_DATA_FROM_CART : 'DELETE_DATA_FROM_CART',
    SUCCESS_DELETE_DATA_FROM_CART : 'SUCCESS_DELETE_DATA_FROM_CART',
    FALIURE_DELETE_DATA_FROM_CART : 'FALIURE_DELETE_DATA_FROM_CART',
}

export default actionTypes