const actionTypes = {
    LOAD_TOKEN : 'LOAD_TOKEN',
    LOAD_TOKEN_SUCCESS : 'LOAD_TOKEN_SUCCESS',
    FAILURE_TOKEN : 'FAILURE_TOKEN',

    START_SELECTED_FACETS : "START_SELECTED_FACETS", 
    SELECTED_FACETS_KEY : "SELECTED_FACETS_KEY",
    SELECTED_FACETS_FALIURE_KEY : "SELECTED_FACETS_FALIURE_KEY",
    REMOVE_FACETS_KEY : "REMOVE_FACETS_KEY",
    EMPTY_ALL_FACET : "EMPTY_ALL_FACET",
    SSR_FACETS : "SSR_FACETS",

    ADD_ADDRESS_START : 'ADD_ADDRESS_START',
    ADD_ADDRESS_SUCCESS : 'ADD_ADDRESS_SUCCESS',
    ADD_ADDRESS_FAIL : 'ADD_ADDRESS_FAIL',
    UPDATE_ADDRESS_START : 'UPDATE_ADDRESS_START',
    UPDATE_ADDRESS_SUCCESS : 'UPDATE_ADDRESS_SUCCESS',
    UPDATE_ADDRESS_FAIL : 'UPDATE_ADDRESS_FAIL',
    DELETE_ADDRESS : 'DELETE_ADDRESS',
    DELETE_ADDRESS_SUCCESS : 'DELETE_ADDRESS_SUCCESS',
    DELETE_ADDRESS_FAIL : 'DELETE_ADDRESS_FAIL',    

    LOAD_SIGNIN_SIGNUP : 'LOAD_SIGNIN_SIGNUP',
    LOAD_SUCCESS_SIGNIN_SIGNUP : 'LOAD_SUCCESS_SIGNIN_SIGNUP',
    FAILURE_SIGNIN_SIGNUP : 'FAILURE_SIGNIN_SIGNUP',
    LOAD_USERDATA : 'LOAD_USERDATA',
    LOAD_SUCCESS_USERDATA : 'LOAD_SUCCESS_USERDATA',
    UPDATE_SUCCESS_USERDATA : 'UPDATE_SUCCESS_USERDATA',
    FAILURE_USERDATA : 'FAILURE_USERDATA'
}
export default actionTypes
