const actionTypes = {
    LOAD_PLP_DATA : 'LOAD_PLP_DATA',
    SET_PLP_KEY : 'SET_PLP_KEY',
    SUCCCESS_PLP_DATA : 'SUCCCESS_PLP_DATA',
    FALIURE_PLP_DATA : 'FALIURE_PLP_DATA',

    START_RECOMMENDED : 'START_RECOMMENDED',
    SUCCESS_RECOMMENDED : 'SUCCESS_RECOMMENDED',
    FALIURE_RECOMMENDED : 'FALIURE_RECOMMENDED',
}

export default actionTypes