const actionTypes = {
    LOAD_HOMEPAGE_DATA : 'LOAD_HOMEPAGE_DATA',
    LOAD_HOMEPAGE_DATA_SUCCESS : 'LOAD_HOMEPAGE_DATA_SUCCESS',
    HOMEPAGE_DATA_FAILURE : 'HOMEPAGE_DATA_FAILURE'
}
export default actionTypes
